//
// Created by wz on 23-11-15.
//

#ifndef FAST_DDS_EXAMPLE_EXAMPLE_BOOST_ASIO_SOCKET_ASYNCSERVER04_ASYNC_ASYNC_SERVER04_CONST_H_
#define FAST_DDS_EXAMPLE_EXAMPLE_BOOST_ASIO_SOCKET_ASYNCSERVER04_ASYNC_ASYNC_SERVER04_CONST_H_

#define MAX_LENGTH  1024*2
#define HEAD_LENGTH 2
#define MAX_RECVQUE  10000
#define MAX_SENDQUE 1000


#endif //FAST_DDS_EXAMPLE_EXAMPLE_BOOST_ASIO_SOCKET_ASYNCSERVER04_ASYNC_ASYNC_SERVER04_CONST_H_
