//
// Created by wz on 23-11-20.
//

#ifndef FAST_DDS_EXAMPLE_EXAMPLE_BOOST_ASIO_SOCKET_MSGJSONIDSERVER_LOGICSERVER_CONST_H_
#define FAST_DDS_EXAMPLE_EXAMPLE_BOOST_ASIO_SOCKET_MSGJSONIDSERVER_LOGICSERVER_CONST_H_
int constexpr MAX_LENGTH = 2048;
int constexpr HEAD_TOTAL_LEN = 4;
int constexpr HEAD_ID_LEN = 2;
int constexpr HEAD_DATA_LEN = 2;
int constexpr MAX_RECVQUE = 10000;
int constexpr MAX_SENDQUE = 1000;

#endif  // FAST_DDS_EXAMPLE_EXAMPLE_BOOST_ASIO_SOCKET_MSGJSONIDSERVER_LOGICSERVER_CONST_H_
