//
// Created by wz on 23-11-16.
//

#ifndef FAST_DDS_EXAMPLE_EXAMPLE_BOOST_ASIO_SOCKET_PROTOBUFSERVER_ASYNCSERVER_CONST_H_
#define FAST_DDS_EXAMPLE_EXAMPLE_BOOST_ASIO_SOCKET_PROTOBUFSERVER_ASYNCSERVER_CONST_H_
int constexpr MAX_LENGTH = 2048;
int constexpr  HEAD_LENGTH =  2;
int constexpr MAX_RECVQUE = 10000;
int constexpr MAX_SENDQUE = 1000;
#endif //FAST_DDS_EXAMPLE_EXAMPLE_BOOST_ASIO_SOCKET_PROTOBUFSERVER_ASYNCSERVER_CONST_H_
